### ISSUE TITLE
Speech - error 404

### ISSUE THREAD

**Issue by gorlik1337** [wit-ai/pywit#103]
This example don't work
https://github.com/wit-ai/pywit#speech
please fix it or delete this repository. If something does not work better, delete it.
```
pi@raspberrypi:~/asist $ python run.py
Traceback (most recent call last):
  File "run.py", line 104, in <module>
    resp = client.speech(f, None, None)
  File "/home/pi/.local/lib/python2.7/site-packages/wit/wit.py", line 102, in speech
    data=audio_file, headers=headers)
  File "/home/pi/.local/lib/python2.7/site-packages/wit/wit.py", line 41, in req
    ' (' + rsp.reason + ')')
wit.wit.WitError: Wit responded with status: 400 (Bad Request)
```

**Comment by blandinw** [comment]
- Your example shows 400, not 404.
- The example code from the README works for me, please make sure you provide a correct content type and access token
- If the issue persists, feel free to comment with code to reproduce + instance id
