### ISSUE TITLE
unexpected keyword argument 'handle_message'"

### ISSUE THREAD

**Issue by nickthejagger** [wit-ai/pywit#107]
hey, i run joke.py and i got this error how to fix it? "TypeError: interactive() got an unexpected keyword argument 'handle_message'"

**Comment by aforaleka** [comment]
Hi @nickthejagger! Are you running joke.py with the latest changes to wit.py? There have been some recent updates to the interactive function in wit.py

**Comment by nickthejagger** [comment]
yeah, of course i do.it's the only reason why i check the update because they update so i can use 'understanding' mode in wit i use visual studio code and they give me this error 
>E1123:Unexpected keyword argument 'handle_message' in method call'

**Comment by aforaleka** [comment]
The error is most likely happening because the definition of the `interactive` function is outdated and cannot take the `handle_message` parameter. Can you try running `pip install wit --upgrade` to get the latest version for the wit package v5.0.0?

**Comment by aforaleka** [comment]
Feel free to reopen the issue if you're still encountering this problem
