### ISSUE TITLE
Issue Installing pywit in Windows

### ISSUE THREAD

**Issue by sumitbinnani** [wit-ai/pywit#11]
Dependency issue while building the file in Windows.

Unable to retrieve libwit_32_linux.a

**Comment by aruna86** [comment]
pywit has dependency on requests.
Was facing the same issue. But after installing requests package, was able to install pywit successfully.
1) So, install requests first:
pip install requests
2) And then:  pip install pywit

**Comment by Marocco2** [comment]
It's wit, not pywit

**Comment by blandinw** [comment]
Unfortunately, we don't have the bandwidth to support Windows right now.
The shared code we use in Ruby/Python/etc is written in Rust and lives at https://github.com/wit-ai/libwit.
We'll gladly accept a pull request that adds a `release.sh` script that will cross-compile to all platforms/arch.
We do apologize for the inconvenience.
