### ISSUE TITLE
Accuracy for Speech to Text

### ISSUE THREAD

**Issue by Tritrita** [wit-ai/pywit#112]
Hi
 
May I know the way to increase the accuracy for the Conversion of Speech to Text.?

Any Help is appreciated.

Thanks,

**Comment by patapizza** [comment]
Hi, what is your app id?

Speech is not a priority for us at the moment. We do keep this in mind but can't provide an ETA on when things will improve. In the meantime, if the current state doesn't work well enough for you, we encourage you to try other solutions (e.g. iOS/Android native speech).

**Comment by Tritrita** [comment]
Thanks much for your response,

To be more clear on our requirement with increasing the accuracy, we are trying to convert Audio to Text
Eg. Recorded IVR Audio (.wav )--> Text

**Comment by l5t** [comment]
As @patapizza said, speech has not been a priority for us in the last few years as most of our community are building for text input (chat bots). We provide a generic speech model that works pretty well for turning speech into commands or actionable data. We also provide the text but as a piece of information only as speech engine usually makes mistakes. So as of now, you can definitely use Wit.ai to transform audio into text (as some of the developers in our community) but we cannot guarantee the accuracy nor help you customize or improve the model. Also we first created this for short speech commands (less than 10sec) this is why you may have issue with longer audio. Our focus may change later this year though.

**Comment by Tritrita** [comment]
Thanks for your response.
I have tried with below 2 Solutions:
**Solution 1:**
I recorded Audio from the mobile which is of 9 sec, but it doesn't work as expected.
**Solution 2:**
I downloaded an Sample Audio from Internet which is of 20 sec ,It works perfectly with 90 percent Accuracy.

**Comment by shashankpr** [comment]
@Tritrita If you want a higher accuracy for your speech-to-text conversion, perhaps you can try using Google Speech API. As an alternative, your recorded audio files can be converted to text using the Google Speech API, then the generated text could be pushed to the Wit.ai service to get your intents & actions.

**Comment by manasomali** [comment]
![image](https://user-images.githubusercontent.com/40079699/110196433-3ef30080-7e23-11eb-910f-7073e23d7da3.png)
I try some services and found this values from my tests.
