### ISSUE TITLE
wit.ai API stoped working

### ISSUE THREAD

**Issue by GTrela** [wit-ai/pywit#115]
While sending a message or audio using  wit.ai python client every time a get response:

> wit.wit.WitError: Wit responded with status: 400 (Bad Request)

I check the token, and it's corrent.

That's the code I use:
`resp = None
with open('test.wav', 'rb') as f:
  resp = client.speech(f, None, {'Content-Type': 'audio/wav'})
print('Yay, got Wit.ai response: ' + str(resp))`

**Comment by stopachka** [comment]
Heyy @GTrela 
- please share your app-id
- please email me an example wav file you are using (stopachka [at] fb [dt] com)

**Comment by stopachka** [comment]
Update: resolved in https://github.com/wit-ai/wit/issues/1158
