### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by vikc07** [wit-ai/pywit#12]
Any plans for python3 support? Documentation mentioned 2.7. Nevertheless, I went ahead and installed it in python3 but got error while running a test script

`Traceback (most recent call last):
  File "test_wit.py", line 1, in <module>
    import wit
ImportError: /usr/local/lib/python3.4/dist-packages/wit.cpython-34m.so: undefined symbol: Py_InitModule`

**Comment by vikc07** [comment]
I ended up forking pywit and fixing pywit.c to allow for Python3 usage. I have created a pull request for it

**Comment by blandinw** [comment]
Thank you, merged #13
