### ISSUE TITLE
Speech to Text longer than 10 seconds

### ISSUE THREAD

**Issue by iUPDev** [wit-ai/pywit#122]
[myspeech.zip](https://github.com/wit-ai/pywit/files/2774339/myspeech.zip)

We noted that there are problems with the "conversion service - speech to text" when the audio file are longer than 10 seconds.

Enclosed (myspeech.zip file) you can find two simple WAV files that we use to understand the process to communicate with Wit service and to perform some tests.

The first one have a duration of 8 seconds, and with this we have not met any kind of issue, here below you can find the output we received from your server:
MacBook-Pro-di-***:~ ******$ cd '/Progetti Personali/Phyton Tutorial/' && '/usr/local/bin/pythonw'  '/Progetti Personali/Phyton Tutorial/Recognize.py'  && echo Exit status: $? && exit 1
{u'entities': {}, u'msg_id': u'1SMUC8cFg6VWTGtQ0', u'_text': u'prova prova Proviamo questa registrazione per vedere se funziona Arrivederci e grazie E quanto cazz'}

The second one has instead a duration of 18 seconds, and with this audio we always receive this error alert:
MacBook-Pro-di-***:~ ******$ cd '/Progetti Personali/Phyton Tutorial/' && '/usr/local/bin/pythonw' '/Progetti Personali/Phyton Tutorial/Recognize.py' && echo Exit status: $? && exit 1
{u'code': u'wit', u'error': u"Something went wrong. We've been notified."}

Could someone kindly help us?
P.s. Of course we are totally available to share others information if needed.
Many thanks.

**Comment by iUPDev** [comment]
Hi,
many thanks for the feedback.

As explained to your colleagues by email (Laurent and Himanshu), your service could be a very important solution for our app.
We have noted a popular demand for an easy and pratic tool that can allow to users to convert audio message in text message.

As explained to your colleagues, we are working on an international and ambitious project, for which we will invest an important budget in marketing and promotional activities.
Of course we are willing to include your name in our strategic partners.
I think this could be a tangible signal to demonstrate that I want to try to build a good relationship between us. I really hope that we can help eachother.

Thanks again, see you soon.
Marco Righetti

**Comment by patapizza** [comment]
Hi Marco,

I can't reproduce:

```
$ curl \
 -H 'Authorization: Bearer xx' -XPOST \
 'https://api.wit.ai/speech?v=20180404' --data-binary @'myspeech2.wav' -H 'Content-Type: audio/wav'
{
  "_text" : "sole scienza programmata tra la fine del 2017 l'inizio del 2018 è rimasto il tema dell'adolescenza programmata se ne discute da anni le case produttrici peggiorerebbe di proposito le prestazioni dei dispositivi più vecchi per spingere gli utenti a comprare quelli nuovi",
  "entities" : { },
  "msg_id" : "xx"
}
```

```                                                                                                                                                                                                                          
 $ curl \
 -H 'Authorization: Bearer xx' -XPOST \
 'https://api.wit.ai/speech?v=20180404' --data-binary @'myspeech1.wav' -H 'Content-Type: audio/wav'
{
  "_text" : "Prova Proviamo questa registrazione per vedere se funziona Arrivederci e grazie E quanto",
  "entities" : { },
  "msg_id" : "xx"
}
```

What is your app id?
