### ISSUE TITLE
Wit object has no attribute 'message'

### ISSUE THREAD

**Issue by jeindustries** [wit-ai/pywit#129]
We are working on a project using Wit.ai. The following code stopped working suddenly and every time we run it, the message saids theres no attribute called 'message'. How can I fix this?

`from wit import Wit

access_token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
client = Wit(access_token)
resp = client.message("set an alarm tomorrow at 7am")`

![Capture](https://user-images.githubusercontent.com/33035329/56679906-1a109c80-6694-11e9-808e-5a83eb174b4a.PNG)

**Comment by jtliao** [comment]
hi @jeindustries, i can't reproduce this, I presume there is an issue importing the project

**Comment by jeindustries** [comment]
Is there any way i can fix this? Uninstalling the project maybe?

**Comment by jtliao** [comment]
not too sure, but I would give that a shot. i tried reproducing with the exact steps from https://github.com/wit-ai/pywit, (beginning with `pip install wit`), and it worked without problems

**Comment by KartikChugh** [comment]
Getting this error.

```
from wit import Wit
client = Wit(<access token>)
client.interactive()
```

`AttributeError: 'Wit' object has no attribute 'interactive'`

and the other commands don't work either.

**Comment by KartikChugh** [comment]
Tried uninstalling and reinstalling but it didn't fix the issue
