### ISSUE TITLE
Is it possible to use interactive() method in speech?

### ISSUE THREAD

**Issue by zume2020** [wit-ai/pywit#136]
Is it possible to use interactive() method in speech?  It would be really  helpful if you can provide any link to documentation or examples regarding [.interactive()](https://github.com/wit-ai/pywit#interactive) method for voice interaction.

**Comment by jtliao** [comment]
Unfortunately, `interactive` does not support speech at the moment. But, `interactive` is just a light wrapper  around other functions that exist, you should be able to have a loop that takes in audio samples, then using similar `prompt` logic to keep the interactive conversation

**Comment by zume2020** [comment]
okey, thanks! @jtliao
