### ISSUE TITLE
Speech recognition is not supported for language: fa

### ISSUE THREAD

**Issue by miladsoor** [wit-ai/pywit#139]
hi i get this error about 3 days ago

{
  "code": "bad-request",
  "error": "Speech recognition is not supported for language: fa"
}== Info: Connection #0 to host api.wit.ai left intact

app id: 58d8b562-bdc6-4ff0-90cf-13a0bf8374a0
what should i do?

**Comment by jtliao** [comment]
Hi @miladsoor, unfortunately we no longer support speech recognition for that language. We began the deprecation process 3 months ago; and hope to bring back the service at some time later this year.
