### ISSUE TITLE
No wit.init()

### ISSUE THREAD

**Issue by rmeertens** [wit-ai/pywit#14]
Hey, 

Just installed the latest wit on my ubuntu, though pip. Unfortunately it does not know the function init(). Anybody has any idea?

**Comment by rmeertens** [comment]
Could it be that the version on pip is NOT the official wit-ai library?
I was able to build it from source, although it took more steps than I liked (had to manually download and rename the lib file and move it to the right folder). 
Maybe it would be a good idea to create an install script or create a copy-paste commands procedure on the website specifically for ubuntu etc.

**Comment by blandinw** [comment]
Hey Roland, it looks like the version on PyPi is the same as on the repo (https://pypi.python.org/pypi/wit/1.1).
I'm not knowledgeable in Python packaging, especially modules written in C.
We'll gladly accept a pull request if you find the time to look at it.

**Comment by rmeertens** [comment]
He man, are you sure? What do you see if you run the following in python:
import wit
dir(wit)


For me the whole init function is missing (also missing in the unofficial library, hence my fast conclusion)

**Comment by andreimarcu** [comment]
Hi @rmeertens, is the file you're working on named wit.py by any chance? 
I just installed pywit from pip and I haven't had that issue.

**Comment by walchko** [comment]
Make sure you installed wit using:

```bash
pip install wit
```

and **not**

```bash
pip install pywit
```

The confusing part is the [official directions](https://wit.ai/docs/python/1.0.0/quickstart) say ``Let’s install the pywit package!`` Which is the wrong package and doesn't have a wit.init() ... it confused me until I noticed the command line to the right of this sentence said ``pip install wit`` and not ``pywit``.

**Comment by blandinw** [comment]
We moved away from audio recording and streaming because:
- many people only needed access to the HTTP API, and audio recording did not make sense for server-side use cases
- dependent on platform, choice best left to developers
- forced us to maintain native bindings as opposed to a pure Pythonic library

**Comment by rmeertens** [comment]
So... how to turn speech into actionable data?

**Comment by blandinw** [comment]
We now expect the developer to pick the best audio recording library for their platform and stream it to POST /speech (https://wit.ai/docs/http/20141022#get-intent-via-speech-link).

**Comment by rmeertens** [comment]
Cool. Any chance of getting an offline Wit interpreter in the future? (downloading your trained intents, and saving everything for upload later)

**Comment by Sultan91** [comment]
Could update info about speech recognition, is post audio file function is working?
