### ISSUE TITLE
Upload multiple audio files to wit.ai Post Speech API

### ISSUE THREAD

**Issue by rishabh-patch** [wit-ai/pywit#140]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about pywit?**
Question:
1. Is there a way to upload multiple audio files to the Post Speech API ?
2. Also, can correct transcriptions be uploaded along with the audio file to be used under "Train My Voice" tab for training?
**What is the current behavior?**
Unable to find the way to do it.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by gondiss** [comment]
Hi Rishabh,
Thanks for your questions. speech API doesn't support bulk upload feature. It is a REST API for real time-time transcription and understanding. 
Support for uploading annotated speech samples is in our near-term plan. I will share your input with the team. thanks

**Comment by rishabh-patch** [comment]
Hi there, many thanks for getting back to me, we as a company have
developed an ecosystem around wit.ai to transcribe phone calls, an
automated process of noise filtering, silence suppression, the LKFS and
DBFS adjustments et.al. we are a communication technology company and
generate almost 200hours of call recordings everyday, we power 3Mn mobile
devices, if you can please help us/allow bulk updates and we can together
make the wit system more potent for Asian voices. We are committed to this
cause and will be happy to contribute to the wit developer community and
share our learnings.

**Comment by rishabh-patch** [comment]
@gondiss  Is there any possibility?

**Comment by jtliao** [comment]
We won't be able to support this
