### ISSUE TITLE
Facing problem while doing speech recognition using python client 

### ISSUE THREAD

**Issue by allencarvallo** [wit-ai/pywit#143]
**CODE**

_from dotenv import load_dotenv_
_import os_
_from wit import Wit_

_load_dotenv()_
_access_token = os.getenv('SERVER_ACCESS_TOKEN')_
_client = Wit(access_token)_
_resp = None_
_with open('milk.wav', 'rb') as f:_
_resp = client.speech(f, {'Content-Type': 'audio/wav'})_
_print()_
_print('Yay, got Wit.ai res_ponse: ' + str(resp))_
_print()_

**ERROR**

Traceback (most recent call last):
File "speech.py", line 15, in
resp = client.speech(f, {'Content-Type': 'audio/wav'})
File "C:\Users\Using Wit with python\venv\lib\site-packages\wit\wit.py", line 87, in speech
resp = req(self.logger, self.access_token, 'POST', '/speech', params,
File "C:\Users\Using Wit with python\venv\lib\site-packages\wit\wit.py", line 40, in req
raise WitError('Wit responded with status: ' + str(rsp.status_code) +
wit.wit.WitError: Wit responded with status: 400 (Bad Request)

**Comment by jtliao** [comment]
Can you verify this works when sending a request through cURL directly?

**Comment by allencarvallo** [comment]
Yes. I have tried a message that i already trained and it worked.
