### ISSUE TITLE
I have created a version in my app. Which parameter should I pass in my code so that it specifically hits this app version? I need this to maintain versioning in my witai app.

### ISSUE THREAD

**Issue by rohitx71** [wit-ai/pywit#147]

**Comment by patapizza** [comment]
Hi,

The API uses the `tag` version parameter. It isn't implemented yet in the Python library. Would you be able to take a stab at it?

**Comment by rohitx71** [comment]
yes, will check that.
If i've created a version 1.0 in my wit app. I need to pass 1.0 as the value of tag in the apis, right?

**Comment by jtliao** [comment]
Yes
