### ISSUE TITLE
Problem in installing wit

### ISSUE THREAD

**Issue by sathish09** [wit-ai/pywit#15]
i tried to install wit via pip install wit. i got this error

`sathish@sathish-desktop:~/pywit$ sudo pip install wit
Downloading/unpacking wit
  Downloading wit-1.1.tar.gz
  Running setup.py (path:/tmp/pip-build-hNjLyq/wit/setup.py) egg_info for package wit
    
Installing collected packages: wit
  Running setup.py install for wit
    Retrieving platform-specific libwit library... libwit-armv6.a
    building 'wit' extension
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ilibwit/include -I/usr/include/python2.7 -c pywit.c -o build/temp.linux-armv7l-2.7/pywit.o
    pywit.c:18:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     static PyObject *pywit_close()
                      ^
    pywit.c:57:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     static PyObject *pywit_voice_query_stop()
                      ^
    arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/pywit.o -Llibwit/lib -lwit -lrt -lsox -lssl -lcrypto -ldl -lpthread -lrt -lgcc_s -lpthread -lc -lm -o build/lib.linux-armv7l-2.7/wit.so
    /usr/bin/ld: cannot find -lssl
    /usr/bin/ld: cannot find -lcrypto
    collect2: error: ld returned 1 exit status
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-hNjLyq/wit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-KLZaBg-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

Retrieving platform-specific libwit library... libwit-armv6.a

running build_ext

building 'wit' extension

creating build

creating build/temp.linux-armv7l-2.7

arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ilibwit/include -I/usr/include/python2.7 -c pywit.c -o build/temp.linux-armv7l-2.7/pywit.o

pywit.c:18:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]

 static PyObject *pywit_close()

                  ^

pywit.c:57:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]

 static PyObject *pywit_voice_query_stop()

                  ^

creating build/lib.linux-armv7l-2.7

arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/pywit.o -Llibwit/lib -lwit -lrt -lsox -lssl -lcrypto -ldl -lpthread -lrt -lgcc_s -lpthread -lc -lm -o build/lib.linux-armv7l-2.7/wit.so

/usr/bin/ld: cannot find -lssl

/usr/bin/ld: cannot find -lcrypto

collect2: error: ld returned 1 exit status

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-hNjLyq/wit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-KLZaBg-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-hNjLyq/wit
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 52: ordinal not in range(128)`

When  i tried it with manual install. i get error in ld

`sathish@sathish-desktop:~/pywit$ sudo python setup.py build
running build
running build_ext
building 'wit' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ilibwit/include -I/usr/include/python2.7 -c pywit.c -o build/temp.linux-armv7l-2.7/pywit.o
pywit.c:18:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 static PyObject *pywit_close()
                  ^
pywit.c:57:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 static PyObject *pywit_voice_query_stop()
                  ^
pywit.c: In function ‘initwit’:
pywit.c:203:16: warning: ‘return’ with a value, in function returning void
         return NULL;
                ^
arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/pywit.o -Llibwit/lib -lwit -lrt -lsox -lssl -lcrypto -ldl -lpthread -lrt -lgcc_s -lpthread -lc -lm -o build/lib.linux-armv7l-2.7/wit.so
libwit/lib/libwit.a: error adding symbols: File truncated
collect2: error: ld returned 1 exit status
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
`

i tried in all versions of wheezy and Jessie and ubuntu mate in raspberry pi. please some one help me solve this problem

**Comment by andreimarcu** [comment]
Hi there, it seems you're missing some dependencies.

Try ```sudo apt-get install python-dev python-pip curl libcurl4-openssl-dev libsox-dev``` and try installing from pip again.

**Comment by blandinw** [comment]
Hi, we improved the documentation around installing pywit. Feel free to reopen if the new version still does not work.
