### ISSUE TITLE
WitError: Wit responded with status: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by melvynawani** [wit-ai/pywit#157]
report a *bug*

**What is the current behavior?**
After a few calls it gives server error. Happened once and i started a new app and it has happened again in the new app. No matter the message it gives the same error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
client.message('Good morning')

**What is the expected behavior?**
To return a response

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
On two different apps. Their ID's are stated below

284119643376853

330927201918526

**An example of an error message it gives**
WitError                                  Traceback (most recent call last)
<ipython-input-4-e23ecaf86fe3> in <module>
----> 1 x= client.message('Good afternoon')
      2 reply_client(x)

~/opt/anaconda3/lib/python3.8/site-packages/wit/wit.py in message(self, msg, context, n, verbose)
     67         if verbose:
     68             params['verbose'] = verbose
---> 69         resp = req(self.logger, self.access_token, 'GET', '/message', params)
     70         return resp
     71 

~/opt/anaconda3/lib/python3.8/site-packages/wit/wit.py in req(logger, access_token, meth, path, params, **kwargs)
     39     )
     40     if rsp.status_code > 200:
---> 41         raise WitError('Wit responded with status: ' + str(rsp.status_code) +
     42                        ' (' + rsp.reason + ')')
     43     json = rsp.json()

WitError: Wit responded with status: 500 (Internal Server Error)

**Comment by chessai** [comment]
This should now be resolved. See https://github.com/wit-ai/wit/issues/2105#issuecomment-860916172
