### ISSUE TITLE
500 errors with python API

### ISSUE THREAD

**Issue by kitchWWW** [wit-ai/pywit#166]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about pywit?**
Bug
**What is the current behavior?**
When running code:
```
from wit import Wit

client = Wit(access_token)
client.message('set an alarm tomorrow at 7am')
```
with my access token as the token from my app: (appid: 238208391312254)
I get a 500 error, rather than a response

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- `pip install wit`
- `python test.py`

**What is the expected behavior?**

no 500 error, API to work as expected

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
(appid: 238208391312254)

**Comment by jayyteee** [comment]
Hey @kitchWWW sorry for the late response. Can you confirm you still have this issue? From the pywit directory can you first checkout master and run `git pull`. Then try running `pip install .` followed by `python examples/basic.py` and see if you are able to get a response by typing in a message there.
