### ISSUE TITLE
Cannot register with GitHub or Facebook account any more?

### ISSUE THREAD

**Issue by ivysoftware** [wit-ai/pywit#22]
I am trying to using wit toolkit for my own application, but it turned to be unconnected by either entrance below.

**Comment by patapizza** [comment]
Are you able to login to your Wit.ai app? What are you trying to do?

**Comment by kingstonlee** [comment]
If you were having problems logging in using Facebook or Github on https://wit.ai/, what worked for me was turning off some of the browser extensions (ex. adblocker, greasemonkey, etc.) and reloading the page.  Hope that helps.
