### ISSUE TITLE
Required actions argument for message

### ISSUE THREAD

**Issue by phpepe** [wit-ai/pywit#31]
This is great, but there is something that I didn't understand 100% about the latest version..
Why is the action argument required if only message method is used?
I think that 'validate_actions(actions)' shouldn't be done on Wit constructor. It's forcing me to setup a dummy set of methods like:

`
def say(session_id, context, msg):
    print(msg)

def merge(session_id, context, entities, msg):
    return context

def error(session_id, context, e):
    print(str(e))

actions = {
    'say': say,
    'merge': merge,
    'error': error,
}`
Doing it is ok and working, but I think this is unnecessary if I only use the message parsing feature.
I'm moving my existing code for 1.0 version to the latest.
Thanks !

**Comment by patapizza** [comment]
I updated the code to display a warning message instead of throwing.
See https://github.com/wit-ai/pywit/commit/7647e03c9d690efc34b9d5d18d4afc81f731094c
