### ISSUE TITLE
Accessing the confidence level in merge or say actions

### ISSUE THREAD

**Issue by rickydunlop** [wit-ai/pywit#33]
When using `run_actions` it seems there is no way to access to the confidence level from the response in the `merge` or `say` actions. 
I would like to decide whether or not to use the response from Wit or to use a generic response based on this.

I know I can do this using the lower level `converse` method but it feels like i'm just copying most of `__run_actions` just to get access to this property, unless I'm missing something obvious?

**Comment by patapizza** [comment]
@rickydunlop The purpose of `run_actions` is to let the bot run in automatic mode. Any custom logic diverting from this behavior should rely on the low-level `converse` API. So you're right, to handle your use case, you would have to copy most of the logic of `__run_actions`.
