### ISSUE TITLE
Adding version to the http requests

### ISSUE THREAD

**Issue by kampta** [wit-ai/pywit#36]
`message` and other HTTP requests need to have a version parameter, failing which a `DEPRECATED` warning is generated.

Also official [documentation](https://wit.ai/docs/http/20160330#versioning-link) says "requests that do not include a version parameter will be rejected."

```
from wit import Wit
client = Wit(TOKEN, actions)
client.message('hi')

{'WARNING': 'DEPRECATED',
 '_text': 'hi',
 'msg_id': 'e6909c8c-818a-4271-a104-027a94b3b11a',
 'outcomes': [{'_text': 'hi',
   'confidence': None,
   'entities': {},
   'intent': 'default_intent'}]}
```

**Comment by patapizza** [comment]
@kampta Sorry about that! I just added API versioning in v3.4.0 - see https://github.com/wit-ai/pywit/commit/d536968a20027c0ba9511dd8882ceb6e01744cd6
