### ISSUE TITLE
Issue running the example codes

### ISSUE THREAD

**Issue by gsquare94** [wit-ai/pywit#41]
I'm unable to run the example code. I already have an app that includes the new story feature. I still get the following error:
`Traceback (most recent call last): File "examples\quickstart.py", line 44, in <module> client.interactive() File "C:\Python34\lib\site-packages\wit\wit.py", line 152, in interactive context = self.run_actions(session_id, message, context, max_steps) File "C:\Python34\lib\site-packages\wit\wit.py", line 126, in run_actions message) File "C:\Python34\lib\site-packages\wit\wit.py", line 119, in __run_actions user_message) File "C:\Python34\lib\site-packages\wit\wit.py", line 83, in __run_actions rst = self.converse(session_id, message, context) File "C:\Python34\lib\site-packages\wit\wit.py", line 75, in converse resp = req(self.access_token, 'POST', '/converse', params, json=context) File "C:\Python34\lib\site-packages\wit\wit.py", line 28, in req ' (' + rsp.reason + ')') wit.wit.WitError: Wit responded with status: 404 (Not Found)`

`rsp.reason()` isn't showing anything. I'm using the server-access token as the only command line argument. Can anyone please specify what I'm doing wrong?

**Comment by patapizza** [comment]
Hi,
Do you still have the issue? Were all your stories saved and passing when you tried?
