### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by vrushabmaitri** [wit-ai/pywit#44]
When tried running template.py throws error TypeError: 'dict' object is not callable, so I changed the line to client = Wit([access_token, actions]) and then it shows error for client.run_actions(session_id, 'your message', {}) **AttributeError: 'Wit' object has no attribute 'run_actions'**.
The same error for client.interactive() in quickstart.py

**Comment by icalF** [comment]
Pip install doesn't work. You need to install from source #20
