### ISSUE TITLE
how to get bot responses in a simple example

### ISSUE THREAD

**Issue by DavidAwad** [wit-ai/pywit#45]
There has to be a clearer explanation on how to actually get the responses from the bot. 

The whole point is for a dev to be able to use it just like I could the chat client in the story editor when I first try this with some hardcoded examples. 

There has to be a **real** quickstart to return JUST the hardcoded  responses of the bot with messages so that the bot acts as a sort of classifier for when someone is first using this platform. 

``` python
client = Wit(access_token, actions)
# simple example, no context supplied, start of conversation
resp = client.converse('yolo-42', 'why are there blue skies?', {})

print(resp)
{'msg': 'Why would I know that? For I am a robot', 'entities': {}, 'confidence': 0.2954891524491307, 'type': 'msg'}
```

It extracts no entities from the incoming message, and returns just the output without anything to update the context with. Something like this I think would help a lot of people who are using it for the first time.

**Comment by l5t** [comment]
can you try pip install --upgrade?

**Comment by patapizza** [comment]
Hey @DavidAwad,

The function you're looking for is probably `run_actions`.
See the example in the [README](https://github.com/wit-ai/pywit#run_actions).
