### ISSUE TITLE
Asyncio Support

### ISSUE THREAD

**Issue by Xowap** [wit-ai/pywit#46]
Hi,

I've started [a port to asyncio](https://github.com/ActivKonnect/pywit) in order to use pywit with an asyncio app.

The question being: are you guys interested by this? Or should I maintain my own fork?

Thanks,
Rémy

**Comment by patapizza** [comment]
Hi @Xowap,

Thank you for working on this.

As asyncio is only available in Python 3.4 or later, we prefer to keep it as-is for now to support Python 2 users.

Julien
