### ISSUE TITLE
Latest version not accessible via pip

### ISSUE THREAD

**Issue by AtheMathmo** [wit-ai/pywit#51]
Hey all.

This is a pretty minor issue and will likely be automatically resolved with time. But it cost me an hour or so today so I thought I'd report it on the off chance of saving someone else.

When trying to install the latest version via pip:

```
Collecting wit==4.0.0
  Could not find a version that satisfies the requirement wit==4.0.0 (from versions: 1.0, 1.1, 2.0, 3.0, 3.1, 3.2, 3.3.0, 3.4.0, 3.4.1, 3.5.0)
No matching distribution found for wit==4.0.0
```

The version seems to be listed here: https://pypi.python.org/pypi/wit . As it's been a few days since the release I thought it best to let you know.

**Comment by xbili** [comment]
Same here!

**Comment by patapizza** [comment]
Sorry about that! It should be available now.
