### ISSUE TITLE
Doesn't support context?

### ISSUE THREAD

**Issue by danqing** [wit-ai/pywit#52]
I believe the message endpoint should accept context for stuff like timezone. I don't think it's supported here.

**Comment by l5t** [comment]
the /message API does support optional context parameter https://wit.ai/docs/http/20160526#get--message-link

**Comment by danqing** [comment]
Yes, but I don't think it's supported by pywit unless I'm missing something. Can you add it?

**Comment by l5t** [comment]
You're right, it is not there ;-) Feel free to send us a Pull Request

**Comment by danqing** [comment]
I don't mind sending in a pull request, but it will be great if you guys can add these basic functionalities so that we don't need to always send in pull request for everything we need to use.. Otherwise it's kind of defeating the point of using a library instead of just calling the HTTP endpoints

**Comment by patapizza** [comment]
@danqing You're now able to pass a context object to message (https://github.com/wit-ai/pywit/commit/346baba57cde139a2386562d8c0681f5357e4fc9).
