### ISSUE TITLE
Unable to run quickstart.py

### ISSUE THREAD

**Issue by adavanisanti** [wit-ai/pywit#53]
Hi - I followed all the instructions for the quickstart tutorial. I can run the bot on the console. However, when I run quickstart.py <wit-token> from command line, I get the below errors. Could you help me resolve this?

File "quickstart.py", line 46, in <module>
    client.interactive()
  File "/Users/adavani/anaconda/lib/python2.7/site-packages/wit/wit.py", line 152, in interactive
    context = self.run_actions(session_id, message, context, max_steps)
  File "/Users/adavani/anaconda/lib/python2.7/site-packages/wit/wit.py", line 126, in run_actions
    message)
  File "/Users/adavani/anaconda/lib/python2.7/site-packages/wit/wit.py", line 106, in __run_actions
    context = self.actions[rst['action']](session_id, dict%28context%29)
TypeError: get_forecast() takes exactly 1 argument (2 given)

**Comment by waylander47** [comment]
Hi adavanisanti, I tried too used it too but had the same issue, this is because it return two arguments, in fact you have to had an other in your function like that 
def get_forecast(context, entities ):
To get directly the context and the entities

**Comment by adavanisanti** [comment]
Thanks @waylander47. I tried with two arguments too but I don't get empty entities and a UUID for context. 

I got it working with HTTP APIs and Python requests.

**Comment by waylander47** [comment]
Hi I have the same problem with pywit, my entities are empty and my context is an uuid.
Does someone know why ?

**Comment by datatec24** [comment]
Hi, 
I have the same problem as you guys. 
But i don"t get how to resolve it, could you please detail a little bit?
Thanks.

**Comment by waylander47** [comment]
Hi @datatec24 ,
I'm waiting for the pywit team's answer.
For the moment I'm using this python package https://github.com/lextoumbourou/PyWit but you can also directcly use the http api.

**Comment by patapizza** [comment]
Hi @datatec24 @adavanisanti @waylander47,

Do you guys still experience the issue?

**Comment by Sultan91** [comment]
Yes

**Comment by Sultan91** [comment]
@waylander47 I've tried  https://github.com/lextoumbourou/PyWit  examples but it gives no response. Is this repo is still working?

**Comment by patapizza** [comment]
@Sultan91 This repository is https://github.com/wit-ai/pywit. Does the quickstart of this repository work for you?

**Comment by Sultan91** [comment]
Original version of PyWit is newer one, little bit different. I've also tried but could not figure out why it's not working.
