### ISSUE TITLE
Processing time is slow 

### ISSUE THREAD

**Issue by WeiHaoEric** [wit-ai/pywit#58]
Hello~ Wit.ai
I just followed the quickstar tutorial and create a story as example.

It's tested good at the beginning.
But now some problems are happened.

I type "weather" with no location and answered it with "location" after receiving robot's "where".
My robot will ask "where" again and answer "sunny" correctly at the 2nd time. 
And ... processing time becomes slow.

Anyone knows about this? 
Thank you

**Comment by patapizza** [comment]
Hi @WeiHaoEric,

Do you use the same session id all the time?

Anybody else experiencing this issue?

**Comment by salehinRafi** [comment]
I encounter the same problem. The question keeps repeating.
