### ISSUE TITLE
Integration with facebook

### ISSUE THREAD

**Issue by muzammilafsar** [wit-ai/pywit#61]
i have created stories and developed python code for that . i need help to integrate it with facebook .

**Comment by mickeyckm** [comment]
maybe this article can help you. 
https://abhaykashyap.com/blog/post/tutorial-how-build-facebook-messenger-bot-using-django-ngrok

**Comment by patapizza** [comment]
There is now a Messenger integration example (#55): https://github.com/wit-ai/pywit/blob/master/examples/messenger.py
