### ISSUE TITLE
__run_actions() calling converse()  with the verbose flag in the reset flag's position

### ISSUE THREAD

**Issue by myearw** [wit-ai/pywit#63]
If I call run_actions() with verbose set to True, then inside the resulting calls to __run_actions() it seems that  my verbose flag gets passed to converse() as the reset flag.  Therefore, I get a reset on every step and my app does not seem to follow my story at all.

If I don't pass a verbose flag to run_actions() then I don't have this problem.

**Comment by erlichmen** [comment]
I second that.

**Comment by TheJimFactor** [comment]
I'm having an issue with this too
