### ISSUE TITLE
Different responses between python and website

### ISSUE THREAD

**Issue by Markboerrigter** [wit-ai/pywit#66]
Hello,

I am using wit.ai to develop a facebook messenger bot.

While testing the bot, I  first made a script in wit.ai and later tried to run this in the facebook app.

When I run the script in wit.ai the bot returns the right answers to my questions. ( Yes when I say Yes and No when I say No. 
In python it does however not do the same. It returns sometimes a stop action and sometimes even the opposite answer.

The only thing I can think of is that wit.ai does not accept the story, it however does run the story in the website.

Thanks in advance!

**Comment by l5t** [comment]
It's probably related to the session id. You will use a new session id to start a new conversation. More info here: https://wit.ai/docs/recipes#integrate-link. If you keep using the same session_id for test, then the model will try to take into account the previous states of the context. Wit use the current context (keys only for now), the previous states of the context (at interaction N-1, N-2….) but also the user message (trait entities) to predict the next action.

**Comment by ssiyue** [comment]
got the same issue...but how to generate a new session id in messenger example ?
