### ISSUE TITLE
from wit import Wit ImportError: No module named wit

### ISSUE THREAD

**Issue by ayazahmadtarar** [wit-ai/pywit#68]
I am trying to use wit in python.I have installed Wit via pip
<img width="841" alt="screen shot 2016-10-22 at 8 43 38 pm" src="https://cloud.githubusercontent.com/assets/8918176/19620501/4077ac6e-9898-11e6-91d7-0e5a802205a6.png">

and error is as below

<img width="697" alt="screen shot 2016-10-22 at 8 44 52 pm" src="https://cloud.githubusercontent.com/assets/8918176/19620511/6dcab7ce-9898-11e6-9c11-aa1061536027.png">

**Comment by patapizza** [comment]
What version of the package do you have?
Do you still experience the issue?

**Comment by lucaschain** [comment]
I got this error today

**Comment by SIMAKK** [comment]
Did you do "pip install wit"

**Comment by lucaschain** [comment]
@SIMAKK yes, indeed

**Comment by ayazahmadtarar-pikessoft** [comment]
@simakk yes installed

**Comment by Pipeliner** [comment]
Python 3.5.2+
wit==4.2.0

same error

**Comment by titogarrido** [comment]
root@tjbot:~/pybot/sb/rpi-arm-raspbian-8.0-1.2.0# pip2.7 install wit
Requirement already satisfied: wit in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: simplejson in /usr/local/lib/python2.7/dist-packages (from wit)
Requirement already satisfied: requests>=0.8.8 in /usr/local/lib/python2.7/dist-packages (from wit)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=0.8.8->wit)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=0.8.8->wit)
Requirement already satisfied: urllib3<1.22,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=0.8.8->wit)
Requirement already satisfied: idna<2.6,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=0.8.8->wit)
root@tjbot:~/pybot/sb/rpi-arm-raspbian-8.0-1.2.0# python2.7
Python 2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wit.py", line 1, in <module>
    from wit import Wit
ImportError: cannot import name Wit

same error on raspberry pi

**Comment by jalees01** [comment]
how you solved this error?? @SIMAKK i am facing the same error right now :(

**Comment by reaganfoxley** [comment]
I am also having this error! If anyone knows how to fix it, please let me know!

I used pip to install it on my raspberry pi

**Comment by patapizza** [comment]
Can you try running from the `wit` folder? Might be due to the directory structure.

@LouisCauchy What was the code you tried?

**Comment by jdnav** [comment]
Have a look to wit directory. It may had been installed in a different python directory version.
Imagine you run "sudo python example.py" and "python" runs with 2.7v (you can check it with "python -V"), you must make sure that wit folder is saved in that python directory version or change "python" version.
