### ISSUE TITLE
Error installing wit library

### ISSUE THREAD

**Issue by salilnavgire** [wit-ai/pywit#7]
$ sudo python setup.py install
running install
running build
running build_ext
building 'wit' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ilibwit/include -I/usr/include/python2.7 -c pywit.c -o build/temp.linux-x86_64-2.7/pywit.o
pywit.c:18:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 static PyObject *pywit_close()
                  ^
pywit.c:57:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 static PyObject *pywit_voice_query_stop()
                  ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pywit.o -Llibwit/lib -lwit -lrt -lsox -lssl -lcrypto -ldl -lpthread -lrt -lgcc_s -lpthread -lc -lm -o build/lib.linux-x86_64-2.7/wit.so
/usr/bin/ld: cannot find -lsox
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by alvations** [comment]
I have similar errors: http://askubuntu.com/questions/638401/how-to-install-wit-ai-and-pywit-with-pip

How should we fix that?

**Comment by Seraf** [comment]
Hello,

Also, using wit package from pip : 
```
# pip freeze | grep wit                                                                                                                                      
wit==1.1
```

And using this example : 
```
import wit

wit.init()

token = 'XXXXXXXXXXXXXXX'
# Let's hack!
print('Response: {}'.format(wit.text_query('ajoute des carottes sur la liste Carrefour', token)))

# Wrapping up
wit.close()
```

I get a : 
```
Traceback (most recent call last):
  File "/home/seraf/Sandbox/lisa-api/testwit.py", line 1, in <module>
    import wit
  File "/home/seraf/Sandbox/lisa-api/wit.py", line 3, in <module>
AttributeError: 'module' object has no attribute 'init'
```

Any idea @patapizza @martinraison  please ?

**Comment by Qwert321123** [comment]
Seraf.
I once had the same issue. You probably have somewhere other file name wit. Try to search it and delete it. It may be somewhere in File System

**Comment by Seraf** [comment]
Hello,

Sorry I thought I deleted this comment as indeed it was a problem about another python file called wit.py which was loaded. Sorry for the noise and thanks for your comment @Qwert321123

**Comment by manasvil** [comment]
i am facing the same issue as you @Seraf @Qwert321123 

Output of print wit:
<module 'wit' from '/usr/lib/python2.7/site-packages/wit/__init__.pyc'>


Error:
Traceback (most recent call last):
  File "text_query.py", line 5, in <module>
    wit.init()
AttributeError: 'module' object has no attribute 'init'


Did a search. Could not find another file named wit.py. Any advice?

**Comment by Piotrek321** [comment]
The same error like this one above. You probably have somewhere file name wit. It might be even in your 
File System. It might be Yours file or You could download it from someones Github (I did this)

**Comment by manasvil** [comment]
@Piotrek321 Thanks for your response! But when I print my Wit path it seems to point to the right one and theres only one file there.

I did a file search on my system using find / -type d -name 'wit' which yielded no results but the expected folder.

**Comment by Piotrek321** [comment]
If you paste "AttributeError: 'module' object has no attribute" to google, the most common reason is that You multiple import module with the same name, or You have somewhere some other file named such as file You want to use. If You are not sure if it is Your case, try to remove whole folder where You downloaded wit, and then try to import "wit" in some of Your program. If it didnt throw error like this:
"ImportError: No module named wit" 
it means that I'm right, and You have other file called wit.
If it didn't, write here and we will try to figure something out:)

**Comment by manasvil** [comment]
@Piotrek321  Yeah it says no module named wit when I delete/rename that file. Where can we go from here? :}

**Comment by Piotrek321** [comment]
After deleting, try to reinstall/download again. But I guess You did.. So.. maybe You will try to use HTTP API?

**Comment by manasvil** [comment]
I moved on to this http://pywit.readthedocs.org/en/latest/

**Comment by Seraf** [comment]
pywit is better imho as their's no sox dependancies and is more friendly with CRUD operations ...

It seems the official python library is forgotten... @lextoumbourou give up to maintain his library as Wit created an official one, so I guess it should be forked and community driven.

**Comment by chandanmaruthi** [comment]
This solved the problem
$ sudo pip uninstall wit
Uninstalling wit:
  /usr/local/lib/python2.7/dist-packages/wit-1.1.egg-info
Proceed (y/n)? Y
you are right there is a package called wit that is causing the trouble.

However I still have this problem
Error:
Traceback (most recent call last):
File "text_query.py", line 5, in 
wit.init()
AttributeError: 'module' object has no attribute 'init'

**Comment by markroxor** [comment]
While installing pywit an error pops up on the console-

>python setup.py build
running build
Retrieving platform-specific libwit library... libwit-64-linux.a
error: [Errno 2] No such file or directory

Can someone suggest a solution?

**Comment by irux** [comment]
markroxor.

Make sure you have curl.

apt-get install curl solve this for me.

**Comment by blandinw** [comment]
Thanks to @andreimarcu, the install process should be smoother. (cf. 5a5371bde)
I'll close this now.
