### ISSUE TITLE
Context is not maintained after stop action.

### ISSUE THREAD

**Issue by smaransmarty** [wit-ai/pywit#76]
The bot is not able to remember the context of the conversation beyond a single sentence. After the stop action immediately the context is cleared. 

Either the converse api timings implemented in run_actions has an issue.

**Comment by patapizza** [comment]
I've just tested, and it's working fine for me.
Are you passing the updated context (the one returned by `run_actions`) at the next call to `run_actions`?

**Comment by smaransmarty** [comment]
Sorry. Is this required? I assumed that context is mapped to session id. Should i maintain the context for the next iterations?.

**Comment by patapizza** [comment]
@smaransmarty You are right: the context is mapped to a session id. However you are responsible for keeping this mapping. Wit.ai treats the context as input and read-only, as the context is managed by your actions.

Hope this helps.
