### ISSUE TITLE
  Problem while installing Wit

### ISSUE THREAD

**Issue by Qwert321123** [wit-ai/pywit#8]
Hi guys. I've tried to install Wit.ai on my Ubuntu 12.04. It's clean, i only have here only basic programs (libcur and libsox are ofc installed).
I used code from this site: https://wit.ai/docs/python/1.0.0/quickstart
And when I'm trying to use pip, or clone frome github i get error:
"Running setup.py install for wit
Retrieving platform-specific libwit library... libwit-64-linux.a
error: No such file or directory
"
and i have no idea what the hell is going on.. Is this caused by my ubuntu? Or what?

I'll be grateful for any help

**Comment by rmeertens** [comment]
Same problem here for me. Did I forget a dependency?

sudo pip install wit
Downloading/unpacking wit
  Downloading wit-1.1.tar.gz
  Running setup.py (path:/tmp/pip-build-TxHY49/wit/setup.py) egg_info for package wit
    
Installing collected packages: wit
  Running setup.py install for wit
    Retrieving platform-specific libwit library... libwit-64-linux.a
    error: [Errno 2] No such file or directory
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-TxHY49/wit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-SUE0Sl-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

Retrieving platform-specific libwit library... libwit-64-linux.a

error: [Errno 2] No such file or directory

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-TxHY49/wit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-SUE0Sl-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-TxHY49/wit
Storing debug log for failure in /home/roland/.pip/pip.log

**Comment by kazemihabib** [comment]
I have a same problem when I try to install it it gaves me this:
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/wit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PYch_5-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/wit
Storing debug log for failure in /root/.pip/pip.log

**Comment by edu2004eu** [comment]
I was experiencing the same issue, and it turns out that I didn't have cURL installed. Can you double-check you have curl installed by running something like `curl --help`?

**Comment by rmeertens** [comment]
I believe I had curl installed at the time. As I upgraded to a newer ubuntu installing now works (but still have other issues). Shall I close this issue?

**Comment by andreimarcu** [comment]
Probably was a curl issue, this should be clearer as of 5a5371b.
Feel free to re-open if you still have issues.
