### ISSUE TITLE
Bot App not opening in Wit.ai

### ISSUE THREAD

**Issue by nirmalrayan** [wit-ai/pywit#90]
There seems to be an issue with the new bot I'm creating. I was unable to save a copy of the final version of the bot because it was throwing error. So decided to refresh the browser to regain control. However, after refreshing, the screen is just blank (like it's loading) but nothing happens.. Kindly look into the same. My bot url is https://wit.ai/nirmalrayan/MediBot
![capture](https://cloud.githubusercontent.com/assets/5275500/26248821/7eebb080-3cc1-11e7-989d-2fb185e8a22b.PNG)

**Comment by patapizza** [comment]
Hey @nirmalrayan, the issue is resolved.
Next time for issues regarding Wit.ai itself (vs the pywit library), please use https://github.com/wit-ai/wit/issues.
